language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: UB85S9FCIRooOdAEZ8jSvO62w7UTW8p7+yCOotMaTTvUDu+plWIx/nMJIu+vQFytdxcgthPhyHF+2GPIsJBBoDvT5rBzkeK1YoYXwlDlz5VTuhXHfi8OYW+tXvRuuX3n6e7sJpfUCraUex1/4yW6V5GAI+8meOf1moe7ox8r2dh3AomzWcouJOC4aReOpRocNiiaUso6ige5KifUunxYkmqlu2CRJvzd6Zwv6F/BDxajDj/Yl7Ud9McwvHJjhZclSMsY04ADj65Tu6j0cl/d5TxT1VEmfhHFJdkGhh9mWaq/w9FeQVVrktQ0Xm4nD1nsPZVduYIYDd+A50gllPe1EJogs9tOPE7AxyHc0GYnjiU0pzEVryU0dVFtz7kKtoUe8wFFehh6mipQCm5XjKkn21nuGBw+cjXn9R52DRElHpbRCPTnbxvF9jcTh92tG+rv/7STcL3h1f/z6e7vaRBPQ0cmE5eKG4LP31LOrOIzWGMv1wb04dxGvebHiWNeXnTbK4fqAgOhkepknM7WLRQdrJlvMdw1NAMya+e8SePNMAUr0MyqO8YW/AlDwsEZ8H7ncEwnUu/OKve/3eE+E0LIqpyfbhIFGcZocsHV15jfCSTXNRPiXO8slC/4AftxrGkO8RH5yZAnjKJXJmhkzNl+fSj21jVxzXqNxUrXpBezVPc=
  - secure: uIwa4n66vlo03i3G8tNodhVP6n605wlrFtPTaPC1mt98l9nalOIk/yEZNIp2DQKRLYiUIIUO4Fb9l6avSlIeCC8/aH/vXCcbxE8bI3URdjG6Nrvazz9cyU4W2qq8YEeFGGkzL9fu6x/IKLA1R2QeFK06+h3N8cxJusnRHSNICwbbLWQPPQIIMHH9/T9k1+PMwG3tkwxjuk0ELP6GIkRbdyOLmaOy9E5wlvtZE3bcq3lljjlXgtejSb0tTg1gGqXUvFr3N/hFeegttlqFEmklZMCtPOUPWl7i17vmpcJHjCLL1QIlps3k1IeBaTu9EsX4JAGFQ2LT3ISyOfVex5AfydSkaqJtnGUPEnlLp6mOTmDKtmBSua18mKop+FNcxNJ//r6TKoqXsf0cLJTBApuHIoHWXspgguUbwKizbRUN6bWs9pILhCbLYv1xZCEtU5HwjnovafysXu7RZXLSUvFcyi8XHJggLcWSMgcrCItjSoMSNOro9VRrAhdj4tA9XUdRNcmUyhlF9DfdsfE499fthPsoNfk9DiviKKOMHXY9vhOl4PrhOKURWZYsEmG92z/A3v7yF49iDi6RRRox2yxGD8670azc5yih3I+vwL5JSNjSqI+Ahb+tv/TL/7RUW8RHTYB08eHhanVCt1M+0iowCZdlIEn2NjVfpLFDc7BpQgc=
